### ISSUE TITLE
How to integrate as stand alone picker?

### ISSUE THREAD

**Issue by bmwertman** [rajeshwarpatlolla/TimePickerForIonicFramework#21]
I really like the way the screen shots of your time picker popup looks, but I'm confused. Can this be implemented as a directive that I call from my own app? Do I need to load some portion of the repo as a script from my index.html page?

**Comment by rajeshwarpatlolla** [comment]
Hi @bmwertman, the time picker has already implemented as a directive only. Please have a look at the below link
http://rajeshwarpatlolla.github.io/TimePickerForIonicFramework/

I have described how to use it. But you need to copy the code in 'app.js' and also 'controllers.js' from the repo.

**Comment by rajeshwarpatlolla** [comment]
Your answer is here https://github.com/rajeshwarpatlolla/ionic-timepicker
