### ISSUE TITLE
Timepicker is not shown when using ionic 1.3.13

### ISSUE THREAD

**Issue by janmande** [rajeshwarpatlolla/TimePickerForIonicFramework#30]
I have tried the latest release on Inioc version 1.3.13 and the timepickers are not shown. Using GapDebug shows the following errors:

GET file:///android_asset/templates/time-picker-12-hour.html net::ERR_FILE_NOT_FOUND
GET file:///android_asset/templates/time-picker-24-hour.html net::ERR_FILE_NOT_FOUND

This is caused by wrong templateUrl in app.js. The preceding ../ should be removed from the template path. Changing this fixes the issue.

**Comment by rajeshwarpatlolla** [comment]
I have tested with `ionic#1.0.0-beta.14`. It is working fine. Have you tested with this version?

**Comment by janmande** [comment]
No, only with the latest Ionic version which is 1.3.13

**Comment by janmande** [comment]
Sorry, yes the ionic version I have tested with is 1.0.0-beta.14 here is my output from ionic info command:

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.26
Cordova CLI: 4.2.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.13
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.0.0

**Comment by rajeshwarpatlolla** [comment]
Please check out the bower component. I tested this and it is working fine.
https://github.com/rajeshwarpatlolla/ionic-timepicker

**Comment by rajeshwarpatlolla** [comment]
Resolved with your pull request. I have updated the ionic version to 'v1.0.0-rc.0-nightly-1150'. And it is working fine with this version also.
