### ISSUE TITLE
Two-way binding

### ISSUE THREAD

**Issue by jason-engage** [rajeshwarpatlolla/TimePickerForIonicFramework#39]
Hi, how do you set 2-way binding with a scope variable? If I change the time, I want it to update my controller's scope variable. Right now the time is appearing on the button, but my variable is not updating.

**Comment by rajeshwarpatlolla** [comment]
I am already updating in the scope of respected controller, with out which i cannot show it on the button. Please check the `slots` variable on the scope. Once you update in the view it will also update in the controller. If you try to access the `$scope.slots.epochTime` variable after you modified the time in the view, you can get the updated value.
`$scope.slots = {epochTime: 12600, format: 12, step: 15};`
